name = "asff"
description = "ada subprogram fuzzy finder"
version = "0.1.0-dev"

authors = ["Damien"]
maintainers = ["Damien <damiensporting@gmail.com>"]
maintainers-logins = ["DamDC91"]

executables = ["asff"]
[[depends-on]]
libadalang = "^23.0.0"
[[depends-on]]
gnatcoll = "^23.0.0"
