name = "asff"
description = "ada subprogram fuzzy finder"
version = "0.1.0"

authors = ["Damien De Campos"]
maintainers = ["Damien <damiensporting@gmail.com>"]
maintainers-logins = ["DamDC91"]

executables = ["asff"]
[[depends-on]]
libadalang = "^24.0.0"
[[depends-on]]
gnatcoll = "^24.0.0"
